tag_id:null-ptr-1-x264
config_command:./configure
build_command:make -j4
build_command_repair:make -j4
clean_command:make clean || true
src_dir:/opt/effFix-benchmark/x264/null-ptr-1-x264/src
bug_type:NULLPTR_DEREFERENCE
bug_file:input/thread.c
bug_procedure:open_file
bug_start_line:54
bug_end_line:55
runtime_dir_pre:/opt/effFix-benchmark/x264/null-ptr-1-x264/pre
runtime_dir_repair:/opt/effFix-benchmark/x264/null-ptr-1-x264/repair
