tag_id:null-ptr-6-lxc
config_command:./autogen.sh && ./configure
build_command:make -j4
build_command_repair:make -j4
clean_command:make clean || true
src_dir:/effFix-experiment/effFix-benchmark/lxc/null-ptr-6-lxc/src
bug_type:NULLPTR_DEREFERENCE
bug_file:src/lxc/af_unix.c
bug_procedure:lxc_abstract_unix_send_credential
bug_start_line:235
bug_end_line:238
runtime_dir_pre:/effFix-experiment/effFix-benchmark/lxc/null-ptr-6-lxc/pre
runtime_dir_repair:/effFix-experiment/effFix-benchmark/lxc/null-ptr-6-lxc/repair
