tag_id:null-ptr-2-p11-kit
config_command:./autogen.sh && ./configure
build_command:make -j4
build_command_repair:make -j4
clean_command:make clean || true
src_dir:/opt/effFix-benchmark/p11-kit/null-ptr-2-p11-kit/src
bug_type:NULLPTR_DEREFERENCE
bug_file:p11-kit/virtual.c
bug_procedure:__infer_globals_initializer_function_info
bug_start_line:2536
bug_end_line:2536
runtime_dir_pre:/opt/effFix-benchmark/p11-kit/null-ptr-2-p11-kit/pre
runtime_dir_repair:/opt/effFix-benchmark/p11-kit/null-ptr-2-p11-kit/repair
