tag_id:null-ptr-19-lxc
config_command:./autogen.sh && ./configure
build_command:make -j4
build_command_repair:make -j4
clean_command:make clean || true
src_dir:/effFix-experiment/effFix-benchmark/lxc/null-ptr-19-lxc/src
bug_type:NULLPTR_DEREFERENCE
bug_file:src/lxc/tools/tool_utils.c
bug_procedure:unknown
bug_start_line:328
bug_end_line:328
runtime_dir_pre:/effFix-experiment/effFix-benchmark/lxc/null-ptr-19-lxc/pre
runtime_dir_repair:/effFix-experiment/effFix-benchmark/lxc/null-ptr-19-lxc/repair
